### ISSUE TITLE
youbot-manipulation (only arm)

### ISSUE THREAD

**Issue by dcps-projekt-tu-berlin** [svenschneider/youbot-manipulation#6]
Google-Translator:

Hello Sven Schneider,
We are currently trying to get a youBot manipulator to run in a student project with your youBot - stack , only the arm without base. We urgently need your expertise to the stack.
The problem is that we can not bring up necessary services at the start, when bringup ( youbot_manipulation_examples bringup.launch ) start environment_server shows a continuous error message and the youBot joint / robot_state_publisher obviously provides no / not enough states .
Could it have to do with the fact that we use only the arm, so then joint_states are missing and the environment_server hungs up?
I 've tried to use the youbot_arm.urdf.xacro from the description , then appeared another error ...
Would you have a tip for us?
Best regards and thanks in advance!

---

Hallo Sven Schneider,
wir versuchen derzeit in einem studentischen Projekt Deinen youbot-manipulation Stack für einen youbot-Manipulator zum laufen zu bekommen, also nur den Arm ohne Base. Wir bräuchten dringend Deine Expertise mit dem Stack.
Das Problem ist dass wir nicht slle nötigen Services an den Start bringen können, beim bringup (youbot_manipulation_examples bringup.launch) startet der environment_server mit einer fortlaufenden Fehlermeldung und der youbot joint/robot_state_publisher liefert offenbar keine/zu wenig states.
Könnte es damit zu tun haben, dass wir nur den Arm nutzen, deshalb dann joint_states fehlen woran sich der environment_server aufhängt?
Ich habe schon versucht das youbot_arm.urdf.xacro aus der description zu verwenden, dann tauchten aber andere Fehler auf...
Hättest Du einen Tipp für uns?
Mit freundlichen Grüßen und Dank im Voraus!

**Comment by svenschneider** [comment]
Dear all,

I'm replying in English, so that more people can follow the discussion.

First of all, it would be helpful to get more information about your system (operating system, ROS version, branch of the repository in use, executed commands, logs, ...). In the following, I assume that you are on the "groovy" branch.
Actually, I have never tried out the youbot-manipulation stack with the standalone arm. Therefore, it is definitely possible that this is an/the issue.

For testing, try out the following steps:
1. If you have not done so yet, change the Ethercat IDs in the "youbot_driver/config/youbot-manipulator.cfg" file from
   
   ```
   [JointTopology]
   ManipulatorJoint1 = 5
   ManipulatorJoint2 = 6
   ManipulatorJoint3 = 7
   ManipulatorJoint4 = 8
   ManipulatorJoint5 = 9
   ```
   
   to
   
   ```
   [JointTopology]
   ManipulatorJoint1 = 1
   ManipulatorJoint2 = 2
   ManipulatorJoint3 = 3
   ManipulatorJoint4 = 4
   ManipulatorJoint5 = 5
   ```
2. In the " youbot-manipulation/youbot_manipulation_examples/ros/launch/youbot_joint_state_publisher.launch" change the _robot_description_ parameter from
   
   ```
   $(find xacro)/xacro.py '$(find youbot_description)/robots/youbot.urdf.xacro'
   ```
   
   to
   
   ```
   $(find xacro)/xacro.py '$(find youbot_description)/robots/youbot_arm_only.urdf.xacro'
   ```
3. In the "youbot-manipulation/youbot_manipulation_examples/ros/launch/youbot_oodl_driver.launch", set the _youBotHasBase_ parameter from _true_ to _false_.
4. Try launching the "bringup.launch" file in the youbot_manipulation_examples package again.

Please let me know, if you then still experience problems.

Best regards
Sven

**Comment by dcps-projekt-tu-berlin** [comment]
Dear Sven,

thanks for your quick reply!

First of all, I am using ros hydro on ubuntu 12.04 with the youbot_description and youbot_oodl from the youbot-ros-pkg, which is preinstalled in the remastered ubuntu distro from kuka.
By the way, I also tried ros electro with exactly the same issues.
1. I setted the joint numbers like you said from the start, without changing them the driver didnt work.
2. I allredy tried it out, I changed it like you said, in that description I am using (youbot-ros-pkg) there is only a "youbot_arm.urdf.xacro" not "...arm_only..."
Result: some more Errors...and many dying processes, I can post them tomorrow. Something like "root transform no multi dof joint config", I thaught there were more faults like before.
3. I did that before

OK, I almost done it like this before, but perhaps the youbot_description is different, now I could try out the youbot_description from "youbot" not from "youbot-ros-pkg", right?

Any other ideas?

Thanx a lot in advance!

**Comment by dcps-projekt-tu-berlin** [comment]
Sorry, ros fuerte, not hydro!

**Comment by svenschneider** [comment]
Dear all,

from your description it seems to me, that your setup is inconsistent:
- The youbot-ros-pkg from [1] only works with ROS versions up to Fuerte (and maybe Groovy). For ROS Hydro you should instead use the youbot_driver_ros_interface [2] with its dependencies [3][4][5][6] (I hope that this list is complete).
- The youbot-manipulation meta-package for ROS Hydro does not include the "youbot_manipulation_examples" package anymore, because all the functionality has been integrated into MoveIt!.

A possible fix for the "Multi DOF joint config" problem could be (depending on which branch of the youbot-manipulation repository you are using):
- Hydro: In the "youbot-manipulation/youbot_moveit/config/youbot.srdf" file, change
  
  ```
  <virtual_joint name="odom" type="fixed" parent_frame="odom" child_link="base_footprint" />
  ```
  
  to
  
  ```
  <virtual_joint name="world" type="fixed" parent_frame="base_link" child_link="base_link" />
  ```
- Groovy: In the "youbot_arm_navigation/ros/config/multi_dof_joints.yaml" file, change
  
  ```
  multi_dof_joints:
  - name: base_joint
    type: Floating
    parent_frame_id: base_footprint # map # odom
    child_frame_id: base_footprint
  ```
  
  to
  
  ```
  multi_dof_joints:
  - name: base_joint
    type: Fixed
    parent_frame_id: base_link
    child_frame_id: base_link
  ```

But to be honest, this is currently more guessing than knowing ;) .

[1] https://github.com/youbot/youbot-ros-pkg
[2] https://github.com/youbot/youbot_driver_ros_interface
[3] https://github.com/youbot/youbot_driver
[4] https://github.com/youbot/youbot_description
[5] https://github.com/youbot/youbot_simulation
[6] https://github.com/youbot/youbot_diagnostics

**Comment by dcps-projekt-tu-berlin** [comment]
Dear Sven,

thanx again, i will try to make my setup consistent, i tried so much, so i mixed up the ros distros yesterday evening, i am actually using fuerte, but I will test it with electric also.

I will try youbot/youbot_description today and set up the rest like you said.

I will give you quick feedback!

Best regards

**Comment by svenschneider** [comment]
Dear all,

if you are running on Fuerte the setup which you described looks fine, so don't switch to Electric. Instead try out the changes which I described under the "Groovy" point in my previous comment.

Best regards
Sven

**Comment by dcps-projekt-tu-berlin** [comment]
Dear Sven,
it works now, even with electric!!!! :D Perfect!!!
After hours and hours so easy with your tipps! Great!
I simply corrected the setup for "multi_dof_joints.yaml" like you said for groovy and changed the xacro-file to "youbot_arm.urdf.xacro" for "youbot_joint_state_publisher.launch". Done!
Thanx a lot, Sven!
Best regards

**Comment by svenschneider** [comment]
Great. I'm closing the issue.
